version: '3.8'

services:

  db:
    image: postgres:12-alpine
    restart: always
    env_file: database.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1591
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
    ports:
    - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres-data:
